name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Setup redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '7'
        auto-start: "true"

    - name: Run tests
      run: cargo test
      env:
        REDIS_URL: redis://127.0.0.1
        CI: true
